### ISSUE TITLE
Error with "python manage.py" cmd

### ISSUE THREAD

**Issue by Anwhss** [martin-sicho/genui#10]
Hi 
This job is really great, but I encountered some small problems when using "python manage.py migrate" and python manage.py runserver
![Screenshot 2022-07-02 195713](https://user-images.githubusercontent.com/102893434/177013122-10abc15b-d27f-43d1-bb7a-49081f1d8676.png)

**Comment by martin-sicho** [comment]
Hi,

thanks for trying out the software and the feedback. The default settings module is `genui.settings.prod`, which is meant for production and, thus, requires the secret to be set explicitly. You can set the environment variable `DJANGO_SETTINGS_MODULE` to `genui.settings.debug`, which runs on localhost and requires no further configuration. Also do not forget to run `python manage.py genuisetup` to initialize genui data structures and other things.

Let me know if it worked and if not I can look into it on more detail.

**Comment by Anwhss** [comment]
Thanks a lot for your response. I really execute these steps but I always have the same error.

**Comment by martin-sicho** [comment]
Ok, I tried to execute just now from master and it seems to work. The following steps at least:

```bash
# install env
git clone git@github.com:martin-sicho/genui.git
cd genui
conda create env -f environment.yml
pip install -r requirements.txt

# spin up database (for example with docker)
# the user is important here because that is what the debug config assumes already exists
docker run -p 5432:5432 -v /tmp/genui_postgres_data:/var/lib/postgresql/data/ --env POSTGRES_USER=genui --env POSTGRES_PASSWORD=genui --env POSTGRES_DB=genui --name postgres_local informaticsmatters/rdkit-cartridge-debian:Release_2021_03_5 

# run django debug server
export DJANGO_SETTINGS_MODULE='genui.settings.debug'
cd src
python manage.py migrate
python manage.py genuisetup
python manage.py runserver
```
So you can try to recreate it (note the use of `export DJANGO_SETTINGS_MODULE='genui.settings.debug'`, maybe you forgot the **export** before?)

**Comment by Anwhss** [comment]
Hello, Martin Sicho. Can you please help me to run the project in my locale? I don't have much time and your project is the only solution, but it doesn't work for me. This is my e-mail address (anwarhssine5@gmail.com), if possible, to contact me for more details. I'm very grateful.

**Comment by martin-sicho** [comment]
Very sorry for the late reply. I was away for some time and did not check GitHub notifications. Let me know if you still need help.
